run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - gocyclo
    - dupl
    - unparam
    - goconst
    - gocritic
    - godot
    - misspell
    - nakedret
    - prealloc
    - stylecheck
    - unconvert
    - whitespace
    - revive
    - copyloopvar

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

# Specific linter settings
linters-settings:
  revive:
    # Recommended configuration from revive's README
    rules:
      - name: exported
        arguments:
          - "disableStutteringCheck"

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3
