definitions:
  UserDto:
    properties:
      id:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server Petstore server.
  title: Swagger Example API
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Create new user
      operationId: CreateUser
      parameters:
      - description: idToken
        in: body
        name: idToken
        required: true
        schema:
          type: string
      - description: username
        in: body
        name: username
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UserDto'
      summary: Create new user
      tags:
      - user
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Get user by userId
      operationId: GetUserByUserId
      parameters:
      - description: userId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get user by userId
      tags:
      - user
swagger: "2.0"
